source "https://rubygems.org"

# GitHub Pages gem
gem "github-pages", group: :jekyll_plugins

# Jekyll plugins
group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
  gem "jekyll-paginate"
  gem "jekyll-gist"
  gem "jekyll-github-metadata"
  gem "jekyll-avatar"
  gem "jekyll-coffeescript"
  gem "jekyll-commonmark-ghpages"
  gem "jekyll-default-layout"
  gem "jekyll-mentions"
  gem "jekyll-optional-front-matter"
  gem "jekyll-readme-index"
  gem "jekyll-redirect-from"
  gem "jekyll-relative-links"
  gem "jekyll-remote-theme"
  gem "jekyll-sass-converter"
  gem "jekyll-swiss"
  gem "jekyll-theme-architect"
  gem "jekyll-theme-cayman"
  gem "jekyll-theme-dinky"
  gem "jekyll-theme-hacker"
  gem "jekyll-theme-leap-day"
  gem "jekyll-theme-merlot"
  gem "jekyll-theme-midnight"
  gem "jekyll-theme-minimal"
  gem "jekyll-theme-modernist"
  gem "jekyll-theme-primer"
  gem "jekyll-theme-slate"
  gem "jekyll-theme-tactile"
  gem "jekyll-theme-time-machine"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby] 
gem "webrick", "~> 1.9"
